#!/bin/sh

dbg_echo () {
  [ -z "$DEBUG_FLAG" ] || echo "$*" >>/${DEBUG_TXT}
  [ "$QUIET" = yes ] || echo "$*"
  return
}

prase_from() {
	[ -z "$FROM" ] && return
	FROM_TYPE=${FROM%%:*}
	FROM=${FROM#*:}
	FROM_DEV=${FROM%%:*}
	FROM_BASIC=${FROM##*:}

	if [ "$FROM_TYPE" != "ISO" -a "$FROM_TYPE" != "DIR" ];then
		dbg_echo "FROM_TYPE=$FROM_TYPE is unknown,Dropping to shell"
		exec sh
	fi
	#by dev
	echo -e "\033[36;1m"
	dbg_echo "try detect disk [$FROM_DEV] by dev..."
	echo -e "\033[0m"
	if [ ! -b "${FROM_DEV}" ];then
		echo -e "\033[35;1m"
		dbg_echo "dev=${FROM_DEV} no exsit,Dropping to shell"
		echo -e "\033[0m"
		# exec sh
	else 
		echo -e "\033[36;1m"
		dbg_echo "\033[35;1m[detect dev] ${FROM_DEV} succ\033[0m"
		echo -e "\033[0m"
		return
	fi
	#by uuid
	echo -e "\033[36;1m"
	dbg_echo "try detect disk [$FROM_DEV] by uuid..."
	echo -e "\033[0m"
	#if [ ! -b "/dev/disk/by-uuid/${FROM_DEV}" ];then
	anytmp=`findfs UUID=${FROM_DEV}`
	if [ ! $? = 0 ];then
		echo -e "\033[35;1m"
		dbg_echo "dev=${FROM_DEV} no exsit,Dropping to shell"
		echo -e "\033[0m"
		# exec sh
	else 
		#anytmp=`ll /dev/disk/by-uuid/${FROM_DEV}`
		#anytmp=/dev/${anytmp##*/}
		echo -e "\033[36;1m"
		dbg_echo "[detect uuid] ${FROM_DEV} - ${anytmp} succ"
		echo -e "\033[0m"
		FROM_DEV=$anytmp
		return
	fi
	#by label
	echo -e "\033[36;1m"
	dbg_echo "try detect disk [$FROM_DEV] by label..."
	echo -e "\033[0m"
	anytmp=`findfs LABEL=${FROM_DEV}`
	#if [ ! -b "/dev/disk/by-label/${FROM_DEV}" ];then
	if [ ! $? = 0 ];then
		echo -e "\033[35;1m"
		dbg_echo "dev=${FROM_DEV} no exsit,Dropping to shell"
		echo -e "\033[0m"
		# exec sh
	else 
		#anytmp=`ll /dev/disk/by-label/${FROM_DEV}`
		#anytmp=/dev/${anytmp##*/}
		echo -e "\033[36;1m"
		dbg_echo "[detect label] ${FROM_DEV} - ${anytmp} succ"
		echo -e "\033[0m"
		FROM_DEV=$anytmp
		return
	fi

	exec sh
}

#mount block dev
mount_dev() {
	device_mnt=$1
	dest=$2
	shift 2
	if [ ! -b "${device_mnt}" ]; then
		return 2
	fi
	#echo "string=mount_cmd  -o $* ${device_mnt} ${dest}"
	if mount -o $* "${device_mnt}" "${dest}" >/dev/null 2>&1; then
		return 0
	else
		if ntfs-3g -o $* "${device_mnt}" "${dest}" >/dev/null 2>&1; then
			return 0
		fi
		return 1
	fi
}

# external_persistent "device/share" "fstype" "mount option" "casper-rw file"
external_persistent () {
  dbg_echo " ... External persistent enabled  ..."
  [ -z $4 ] && CASPER=geexbox || CASPER="$4"

  # create directory
  mkdir /persistent
  mount -t tmpfs tmpfs /persistent
  mkdir /persistent/persistent /persistent/data /persistent/etc

  if [ "$2" = "cifs" -o "$2" = "nfs" ] ; then
    PERSISTENT_TMP=/mnt/geexbox
    MNT_OPTION_PERSISTENT="bind"
    MNT_TYPE_PERSISTENT="none"
  else
    # ntfs
    PERSISTENT_TMP=/persistent-tmp
    MNT_OPTION_PERSISTENT="rw,noatime"
    MNT_TYPE_PERSISTENT="ext2"
    mkdir /persistent-tmp
    mount -t ext2 -o rw,noatime /mnt/$4 /persistent-tmp
  fi

  # create our own directory
  for d in bin boot root etc firmware lib sbin sys usr var video ; do
    mkdir -p $PERSISTENT_TMP/$d
  done

  # restore
  for d in bin boot etc firmware lib sbin sys usr var ; do
    cp -R $PERSISTENT_TMP/$d /persistent
  done

  # create *.mount files

   mkdir -p /persistent/lib/systemd/system
   mkdir -p /persistent/etc/systemd/system/remote-fs.target.wants
   cat > /persistent/lib/systemd/system/data.mount << EOF
[Unit]
Description=Mount data

[Mount]
What=$1
Where=/data
Type=$2
Options=$3

[Install]
WantedBy=remote-fs.target
EOF

  cat > /persistent/lib/systemd/system/persistent.mount << EOF
[Unit]
Description=Mount persistent
After=data.mount

[Mount]
What=/data/$CASPER
Where=/persistent
Type=$MNT_TYPE_PERSISTENT
Options=$MNT_OPTION_PERSISTENT

[Install]
WantedBy=remote-fs.target
EOF

  cat > /persistent/lib/systemd/system/root.mount << EOF
[Unit]
Description=Mount root
After=persistent.mount

[Mount]
What=/persistent/root
Where=/root
Type=none
Options=bind

[Install]
WantedBy=remote-fs.target
EOF

  ln -s /lib/systemd/system/data.mount /persistent/etc/systemd/system/remote-fs.target.wants/data.mount
  ln -s /lib/systemd/system/persistent.mount /persistent/etc/systemd/system/remote-fs.target.wants/persistent.mount
  ln -s /lib/systemd/system/root.mount /persistent/etc/systemd/system/remote-fs.target.wants/root.mount

  # umount /persistent-tmp if needed
  [ "$2" = "ntfs" ] && sync && umount /persistent-tmp

}

# do_cache file 
do_cache () {
  mkdir -p /cache
  dbg_echo " ... copying $1 to ram ..."
  mount -t tmpfs tmpfs /cache
  cp /mnt/$1 /cache/rootfs
  dbg_echo " ... Done ..."
}

# install busybox symlinks
/bin/busybox --install -s

export PATH=/sbin:/bin

# mount required filesystems
busybox mount -t proc none /proc
busybox mount -t sysfs none /sys

# prepare /dev
mount -t devtmpfs devtmpfs /dev
echo '/bin/mdev' > /proc/sys/kernel/hotplug
mdev -s

# splash
/bin/ply-image /plymouth/splash.png

# parse kernel cmdline
for arg in $(cat /proc/cmdline); do
  case $arg in
      from=*)
      FROM="${arg#from=}"
      FROM_FLAG="yes"
      ;;
    root=*)
      ROOT="${arg#root=}"
      ;;
    rootfs=*)
      ROOTFS="${arg#rootfs=}"
      ;;
    data=*)
      DATA="${arg#data=}"
      ;;
    init=*)
      INIT="${arg#init=}"
      ;;
    quiet)
      QUIET=yes
      ;;
    persistent*)
      PERSISTENT="${arg#persistent=}"
      [ -z "$PERSISTENT" ] && PERSISTENT=casper-rw
      [ "$PERSISTENT" = persistent ] && PERSISTENT="/casper-rw"
      ;;
    nocache)
      NOCACHE=yes
      ;;
    ro|rootro)
      ROOT_MODE=ro
      ROOT_MODE_PART=ro
      ;;
    rw|rootrw)
      ROOT_MODE=rw
      ROOT_MODE_PART=rw
      ;;
    nfsroot=*)
      NFSROOT="${arg#nfsroot=}"
      ;;
    smbroot=*)
      SMBROOT="${arg#smbroot=}"
      ;;
    ip=*)
    IP="${arg#ip=}"
      ;;
    external-persistent)
      EXTERNAL_PERSISTENT=1
      ;;
    initshell)
      echo "Dropping to shell as requested"
      exec sh
	   ;;
    debug)
	   DEBUG_FLAG="yes"
	   DEBUG_TXT="initrd.log"
      ;;
  esac
done

# prase FROM parameter
prase_from

# if rootro, always mount root as r/o
# if rootrw, always mount root as r/w
# if neither, mount root as r/w only if persistent is enabled and we're
# mounting a partition (not a disk); otherwise, mount root as r/o
if [ -z "$ROOT_MODE" ]; then
  ROOT_MODE=ro
  if [ -n "$PERSISTENT" ]; then
    ROOT_MODE_PART=rw
  else
    ROOT_MODE_PART=ro
  fi
fi

#try to from iso or dir 
if [ -n "$FROM_FLAG" ]; then
	mkdir -p /.partition
	mkdir -p /.cache
#		if mount -o ro "$FROM_DEV" /.partition >/dev/null 2>&1; then
	if mount_dev "$FROM_DEV" /.partition $ROOT_MODE_PART; then
		echo -e "\033[36;1mmount FROM_DEV=$FROM_DEV sucess\033[0m"
		dbg_echo "mount FROM_DEV=$FROM_DEV sucess"
		case $FROM_TYPE in
			ISO)	
			mkdir -p /.temp
			
			if mount -o loop,ro /.partition/$FROM_BASIC /.temp >/dev/null 2>&1; then
				if ! mount -t tmpfs tmpfs /.cache >/dev/null 2>&1; then
					dbg_echo "get tmpfs failed"
					exec sh
				fi
				cp /.temp/rootfs /.cache/rootfs
				if ! mount --move /.cache /mnt >/dev/null 2>&1; then
					dbg_echo "ISO deal failed: mount --move"
					exec sh
				fi
				umount /.temp
				umount /.partition
				echo -e "\033[36;1mmount FROM_BASIC=$FROM_BASIC sucess\033[0m"
				dbg_echo "mount FROM_BASIC=$FROM_BASIC sucess"
				if mount -t squashfs /mnt/rootfs /squashfs >/dev/null 2>&1; then
				        dbg_echo "found."
				        FOUND_ROOTFS=yes
				else
					dbg_echo "failed, cannot mount squashfs."
				    umount /mnt
					umount /.partition
			    fi
			    if [ -n "$PERSISTENT" ]; then
				PERSISTENT_DEV=${PERSISTENT%%:*}
				PERSISTENT_FILE=${PERSISTENT##*:}
				if ! mount_dev "$PERSISTENT_DEV" /.partition $ROOT_MODE_PART; then
				    dbg_echo "PERSISTENT(DEV=$PERSISTENT_DEV,FILE=$PERSISTENT_FILE) mount failed"
				    exec sh;
				fi
			    fi	
			else
				echo -e "\033[31;1mmount FROM_BASIC=$FROM_BASIC failed\033[0m"
				dbg_echo "mount FROM_BASIC=$FROM_BASIC failed"
				umount /.partition	
				exec sh
			fi
			;;
			DIR)
				if [ -z "$PERSISTENT" ] ; then
					mount -t tmpfs tmpfs /.cache					
					cp /.partition/${FROM_BASIC}/rootfs /.cache/rootfs
					mount --move /.cache /mnt
					ROOTFS=/mnt/rootfs
					umount /.partition
				else
					ROOTFS=/.partition/${FROM_BASIC}/rootfs
				fi
			
				if mount -t squashfs $ROOTFS /squashfs >/dev/null 2>&1; then
				        dbg_echo "found."
				        FOUND_ROOTFS=yes
				else
					dbg_echo "failed, cannot mount squashfs."
					umount /.partition
			       fi

			       

			;;
		esac
	else
		echo -e "\033[31;1mmount FROM_DEV=$FROM_DEV failed\033[0m"
		deg_echo "mount FROM_DEV=$FROM_DEV failed"
		exec sh
	fi
fi

# try to mount the rootfs specified in cmdline ... and wait for slow device
[ -z "$ROOT" -a "$ROOTFS" = flat ] && ROOTFS="/rootfs"
[ -z "$ROOTFS" ] && ROOTFS="/rootfs"
if [ -z "$FROM_FLAG" -a -n "$ROOT" ]; then
  COUNT="0 1 2 3 4 5 6 7 8 9"
  for i in $COUNT; do
    dbg_echo -n "[$i] Trying root=$ROOT as requested..."
    if mount -o $ROOT_MODE $ROOT /mnt >/dev/null 2>&1; then
      if [ "$ROOTFS" = flat ]; then
        dbg_echo "found."
        FOUND_ROOTFS=yes
        break
      elif [ "$EXTERNAL_PERSISTENT" = 1 ] ; then
        FSTYPE=`grep "$ROOT" /proc/mounts | cut -d" " -f3`
        do_cache $ROOTFS       
        external_persistent $ROOT $FSTYPE "rw,noatime" $PERSISTENT
        ROOTFS=/rootfs
        mount -r /mnt
        umount /mnt || umount -l /mnt
        mount --move /cache /mnt         
        mount -t squashfs /mnt/$ROOTFS /squashfs >/dev/null 2>&1
        dbg_echo "found."
        FOUND_ROOTFS=yes
        break
      elif mount -t squashfs /mnt/$ROOTFS /squashfs >/dev/null 2>&1; then
        dbg_echo "found."
        FOUND_ROOTFS=yes
        break
      else
        dbg_echo "failed, cannot mount squashfs."
        umount /mnt
      fi
    else
      dbg_echo "failed, cannot mount device."
    fi
    sleep 1
  done
  [ -n "$FOUND_ROOTFS" ] || unset ROOT
  unset FOUND_ROOTFS
fi

## smbroot or nfsroot
if [ -z "$FROM_FLAG" -a -n "$SMBROOT" -o -n "$NFSROOT" ] ; then
  # network up
  if [ -z "$IP" ] ; then
    ifconfig eth0 up >/dev/null 2>&1
    udhcpc -s /bin/assign-ip >/dev/null 2>&1
  fi

  if [ -n "$SMBROOT" ] ; then
    s=`echo $SMBROOT | cut -d: -f1`
    u=`echo $SMBROOT | cut -d: -f2`
    p=`echo $SMBROOT | cut -d: -f3`
    [ -n "$u" -a -n "$p" ] && OP="-o user=$u,password=$p" || OP=""
    NET=$s
  else
    NET=$NFSROOT
    OP="-o nolock,$ROOT_MODE_PART"
  fi
  
  dbg_echo "Trying $NET as requested..."
  ROOT=/mnt
  
  if mount $NET $OP /mnt >/dev/null 2>&1; then
    dbg_echo " ... $NET is mounted ..."
    do_cache $ROOTFS
    if [ "$EXTERNAL_PERSISTENT" = 1 -a "$ROOT_MODE" = rw ] ; then
      [ -n "$NFSROOT" ] && external_persistent $NFSROOT nfs "nolock,rw"
      [ -n "$SMBROOT" -a -n "$OP" ] && external_persistent $s cifs "iocharset=utf8,user=$u,password=$p"
      [ -n "$SMBROOT" -a -z "$OP" ] && external_persistent $s cifs "iocharset=utf8"
    fi
    umount /mnt
    mount --move /cache /mnt
    if mount -t squashfs /mnt/rootfs /squashfs >/dev/null 2>&1; then
      dbg_echo "found."
      FOUND_ROOTFS=yes
    else
      dbg_echo -n "failed, cannot mount squashfs."
      umount /mnt
    fi
  else
    dbg_echo -n "failed, cannot mount $NET."
  fi
  [ -n "$FOUND_ROOTFS" ] || unset ROOT
  unset FOUND_ROOTFS
fi

# ...otherwise just scan the block devices for rootfs
if [ -z "$FROM_FLAG" -a -z "$ROOT" ]; then
  dbg_echo "Scanning for root device:"
  cd /sys/block
  for i in 0 1 2 3 4 5 6 7 8 9; do
    for dev in *; do
      echo $dev | grep -q loop && continue
      echo $dev | grep -q ram && continue
      dbg_echo -n "[$i] Trying $dev..."
#      if mount -o $ROOT_MODE /dev/$dev /mnt >/dev/null 2>&1; then
		if mount_dev /dev/$dev /mnt $ROOT_MODE; then
        ROOT_DEV=$dev
        if [ `cat /sys/block/$ROOT_DEV/device/type` -eq 5 ]; then
          ROOT_TYPE=cdrom
        else
          ROOT_TYPE=disk
        fi
      else
        dbg_echo -n "[$i] Trying ${dev}1..."
        if ! mount -o $ROOT_MODE_PART /dev/${dev}1 /mnt >/dev/null 2>&1; then
          dbg_echo "failed, cannot mount device."
          continue
        fi
        ROOT_DEV=${dev}1
        ROOT_TYPE=disk
      fi
      if [ "$ROOT_TYPE" = cdrom -a -z "$NOCACHE" ]; then
        mkdir -p /cache
        mount -t tmpfs tmpfs /cache
        cp /mnt/$ROOTFS /cache/rootfs
        ROOTFS=/rootfs
        umount /mnt
        eject -s $ROOT_DEV >/dev/null 2>&1 || eject $ROOT_DEV >/dev/null 2>&1
        mount --move /cache /mnt
      fi
      if mount -t squashfs /mnt/$ROOTFS /squashfs >/dev/null 2>&1; then
        dbg_echo "found."
        FOUND_ROOTFS=yes
        break
      else
        dbg_echo "failed, cannot mount squashfs."
        umount /mnt
      fi
    done
    [ -n "$FOUND_ROOTFS" ] && break
    sleep 1
  done
  cd /
fi

[ -z "$INIT" ] && INIT=/sbin/init

if [ "$ROOTFS" = flat ]; then
  if [ ! -x /mnt/$INIT ]; then
    echo "Cannot find a valid root filesystem, dropping to shell"
    exec sh
  fi
  mount --move /mnt /newroot
else
  if [ ! -x /squashfs/$INIT ]; then
    echo "Cannot find a valid root filesystem, dropping to shell"
    exec sh
  fi

  # setup aufs
  if [ -n "$PERSISTENT" -a -z "$EXTERNAL_PERSISTENT" ]; then
   DATA=/mnt/$PERSISTENT
   PERSISTENT_OPT="-o loop -t ext2"
   if [ -n "$FROM_FLAG" ];then
	case $FROM_TYPE in
		ISO)
			DATA=/.partition/$PERSISTENT_FILE
		;;
		DIR)
			DATA=/.partition/$FROM_BASIC/casper-rw
		;;
	esac
   fi
   [ ! -f "$DATA" ] && unset DATA && unset PERSISTENT_OPT
  fi
  if [ -n "$DATA" ]; then
    if ! mount $PERSISTENT_OPT -o rw,noatime $DATA /rw; then
      echo "Cannot mount data partition, using tmpfs instead"
      unset DATA
	   exec sh
    fi
  fi
  [ -z "$DATA" -a -z "$EXTERNAL_PERSISTENT" ] && mount -t tmpfs none /rw
  [ "$EXTERNAL_PERSISTENT" = 1 ] && mount --move /persistent /rw
  if ! mount -t aufs -o br=/rw:/squashfs none /newroot; then
    echo "Cannot mount aufs, dropping to shell"
    exec sh
  fi

  # move backed filesystems inside newroot otherwise aufs won't work properly
  mkdir -p /newroot/run
  mount -t tmpfs -o mode=0755,nosuid,nodev tmpfs /newroot/run
  mkdir -p /newroot/.data /newroot/.squashfs /newroot/.root
  mount --move /rw /newroot/.data
  mount --move /squashfs /newroot/.squashfs
  mount --move /mnt /newroot/.root
  mkdir -p /newroot/dev
  mkdir -p /newroot/run/initramfs/bin /newroot/run/initramfs/sbin /newroot/run/initramfs/lib 
  cp -P /bin/busybox /bin/sh /newroot/run/initramfs/bin/
  cp -P /bin/shutdown /newroot/run/initramfs/
  cp -P /lib/* /newroot/run/initramfs/lib
  cp -P /sbin/mount.ntfs /newroot/run/initramfs/sbin
  cp -P /bin/ntfs-3g /newroot/run/initramfs/bin
fi

INIT_ARGS=`cat /proc/cmdline`
mknod /newroot/dev/kmsg c 1 11 >/dev/null 2>&1

# Reset kernel hotplugging
echo "" > /proc/sys/kernel/hotplug
umount /sys
umount /dev
umount /proc


# Change to the new root partition and execute /sbin/init
if ! exec /bin/busybox switch_root /newroot $INIT $INIT_ARGS; then
  echo "Failed, dropping to shell"
  /bin/busybox mount -t proc none /proc
  /bin/busybox mount -t sysfs none /sys
  exec sh
fi

